services:
  - type: web
    name: expense-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn expense_tracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: expense_tracker.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString

databases:
  - name: expense-db
    plan: free
